# Generated by Django 5.1.6 on 2025-02-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trmnl", "0004_alter_device_last_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("plugins", models.JSONField()),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="events",
                        to="trmnl.Schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleDeviceMapping",
            fields=[
                ("id", models.BigAutoField(primary_key=True)),
                (
                    "schedule",
                    models.ForeignKey(on_delete=models.CASCADE, to="trmnl.Schedule"),
                ),
                (
                    "device",
                    models.ForeignKey(on_delete=models.CASCADE, to="trmnl.Device"),
                ),
            ],
        ),
    ]
