# Generated by Django 5.1.7 on 2025-03-15 00:08

import trmnl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trmnl", "0005_create_schedule_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="timezone",
            field=models.CharField(
                choices=trmnl.models.timezone_choices,
                max_length=64,
                null=True,
            ),
        ),
    ]
