# Generated by Django 5.1.7 on 2025-03-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trmnl', '0006_add_device_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='refresh_rate',
            field=models.IntegerField(default=900),
        ),
        migrations.AddField(
            model_name='screen',
            name='plugin',
            field=models.TextField(null=True),
        ),
    ]
